name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  
publish_to: none

dependencies:
  calculator:
    path: 'packages/calculator'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
